"""Generate reference/t-table.md from the dependency-free statlib."""

from pathlib import Path

from statlib import t_ppf

levels = [(0.80, "80%"), (0.90, "90%"), (0.95, "95%"), (0.98, "98%"), (0.99, "99%"), (0.999, "99.9%")]
dfs = list(range(1, 31)) + [40, 50, 60, 80, 100, 120, 1000]

lines = [
    "# t-distribution table (critical values t\\*)",
    "",
    "Two-sided confidence levels. For a **one-tailed** test with significance level α, use the column whose",
    "two-sided confidence is 1 − 2α (for example, a one-tailed α = 0.05 uses the **90%** column).",
    "",
    "Row `1000` approximates the normal curve (df = ∞): z\\* = 1.282, 1.645, 1.960, 2.326, 2.576, 3.291.",
    "",
    "| df | " + " | ".join(label for _, label in levels) + " |",
    "|---|" + "|".join("---" for _ in levels) + "|",
]
for df in dfs:
    cells = [f"{t_ppf(1 - (1 - c) / 2, df):.3f}" for c, _ in levels]
    lines.append(f"| {df} | " + " | ".join(cells) + " |")
lines += ["", "*Generated by `scripts/make_t_table.py` using `scripts/statlib.py`, which matches published tables to 5 decimal places.*", ""]

out = Path(__file__).resolve().parents[1] / "reference" / "t-table.md"
out.write_text("\n".join(lines), encoding="utf-8")
print("wrote", out, "with", len(dfs), "rows")
